### PR TITLE
Show users numbers of how they've voted

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by inglesp** [comment]
This was requested in IRC.

**Comment by snim2** [comment]
This is probably a silly question, but does this make the numbers visible to the users who are voting?

**Comment by inglesp** [comment]
Not a silly question -- yes it does.  You'll see something like:

image

**Comment by snim2** [comment]
I'm not sure about the wisdom of this, I think it is likely to discourage people to go to talks by first time speakers, and so on. Is it possible to make this information only available to users in an admin group, or similar?

**Comment by ghickman** [comment]
@snim2 – having looked at the code those counts are the user specific totals =)

**Comment by snim2** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaah, apologies :)

**Comment by ghickman** [comment]
This all looks good to me, are you happy with it too @snim2?

**Comment by snim2** [comment]
Yes, sounds good!

**Pull request merged**
