### PR TITLE
Show a 404 when an object is not found, and do not duplicate votes

### PR DESCRIPTION
**Pull request by meshy**

### CODE REVIEW

**Comment by ghickman** [comment]
@meshy – nice one!

Would you mind updating the migration? I changed the existing ones when I added the custom user model.

**Comment by meshy** [comment]
Sure --- having a sudden deplyment issue -- will get back to this asap

**Comment by ghickman** [comment]
:+1:

**Comment by meshy** [comment]
Sorry it took so long!

**Pull request merged**
